### ISSUE TITLE
TypeError: r2 is not a function

### ISSUE THREAD

**Issue by dturkington49** [splitio/cloudflare-workers-template#5]
[wrangler.txt](https://github.com/splitio/cloudflare-workers-template/files/9057000/wrangler.txt)

I am instrumenting my own version of this template repository and I am receiving the following error message:

`[mf:err] TypeError: r2 is not a function
    at Ye (/private/Users/dturkington/repos/cloudflare-worker-split-io/node_modules/@splitsoftware/splitio-commons/esm/utils/settingsValidation/index.js:153:28)
    at /private/Users/dturkington/repos/cloudflare-worker-split-io/node_modules/@splitsoftware/splitio-sync-tools/lib/esm/settings/index.js:21:22
    at new Mt (/private/Users/dturkington/repos/cloudflare-worker-split-io/node_modules/@splitsoftware/splitio-sync-tools/lib/esm/settings/index.js:34:12)
    at ai (/private/Users/dturkington/repos/cloudflare-worker-split-io/src/index.ts:204:24)
    at Object.scheduled (/private/Users/dturkington/repos/cloudflare-worker-split-io/src/index.ts:146:12)
    at /Users/dturkington/repos/cloudflare-worker-split-io/node_modules/@miniflare/core/src/standards/event.ts:340:19
    at /Users/dturkington/repos/cloudflare-worker-split-io/node_modules/@miniflare/shared/src/event.ts:29:9
    at EventTarget.<anonymous> (/Users/dturkington/repos/cloudflare-worker-split-io/node_modules/@miniflare/shared/src/event.ts:77:9)
    at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at EventTarget.dispatchEvent (node:internal/event_target:585:26)`

I have attached my wrangler.toml as a wrangler.txt file. I have enabled Durable Objects on my account. This error message appears in both local and non local mode. I was not aware that r2 was required in this case. I receive this error message every time the cron runs. And as a result, all my splits incorrectly return "control" treatment.

Any help is much appreciated! Thank you!

**Comment by EmilianoSanchez** [comment]
Hi @dturkington49 ,

I am sorry I wasn't able to check this issue before. 

The issue might be coming from an error in one of our dependencies, specifically `@splitsoftware/splitio-sync-tools` version 0.1.0. 
We have updated this template repository and it is using `@splitsoftware/splitio-sync-tools` 0.2.0 now.
